## To fix the permission issues, run these commands on the host machine
# Create the directories if missing
#sudo mkdir -p /opt/squid/data/cache
#sudo mkdir -p /opt/squid/data/logs

# Give them the same UID:GID as the Squid user inside the container
#sudo chown -R 13:13 /opt/squid/data/cache /opt/squid/data/logs

services:
  squid:
    image: ubuntu/squid
    container_name: squid-proxy
    restart: always
    ports:
      - "3128:3128"
    volumes:
      - /opt/squid/conf/squid.conf:/etc/squid/squid.conf
      - /opt/squid/conf/strict_whitelisted_domains.list:/etc/squid/strict_whitelisted_domains.list
      - /opt/squid/data/cache:/var/spool/squid
      - /opt/squid/data/logs:/var/log/squid


